[greeting]
  messages = [
    "Запущен и готов служить!",
    "У контакта ужасный флуд-контроль :(",
    "Писать ботов не так-то просто, как кажется!",
    "Привет, странствующий путник!"
  ]

[memes]
  # Группа, из которой брать мемы
  group_id = "-86441049"

[translate]
  # API ключ для Яндекс.Переводчика
  key = ""

[weather]
  # API ключ для сервиса OpenWeather
  key = ""

[admin]
  # Список ID администраторов для модуля администрации
  admins = [1]

[dialogflow]
  # Включить ли модуль dialogflow
  enabled = false